version: "3.9"

services:
  identity:
    build: ./services/identity
    container_name: identity-service
    ports:
      - "3000:3000"
    networks:
      - newzone-net

  metadata:
    build: ./services/metadata
    container_name: metadata-service
    ports:
      - "3001:3000"
    networks:
      - newzone-net

  consensus:
    build: ./services/consensus
    container_name: consensus-service
    ports:
      - "3002:3000"
    networks:
      - newzone-net

  storage:
    build: ./services/storage
    container_name: storage-service
    ports:
      - "3003:3003"
    networks:
      - newzone-net

  gateway:
    build: ./services/gateway
    container_name: gateway-service
    ports:
      - "3004:3004"
    networks:
      - newzone-net

networks:
  newzone-net:
    driver: bridge